version: '3.0'

services:
  pg:
    image: postgres:13-alpine
    container_name: pg-multi-vendor-ecommerce
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi-vendor-ecom
    ports:
      - 5432:5432
    volumes:
      - pg-multi-vendor-ecom:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6-alpine
    container_name: redis-multi-vendor-ecommerce
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-multi-vendor-ecom:/data

  mongo:
    image: mongo:4.4
    container_name: mongo-multi-vendor-ecommerce
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNANE=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    volumes:
      - mongo-multi-vendor-ecom:/data/db
    restart: always
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper-multi-vendor-ecommerce
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    volumes:
      - zookeeper-data:/data

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-multi-vendor-ecommerce
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch-multi-vendor-ecommerce
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node # single-node or multi-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" #Recomended to set memory limits
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

# UI FOR ALL SERVICES
  redis-ui:
    image: redislabs/redisinsight:latest
    container_name: redis-ui-multi-vendor-ecommerce
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - redis

  mongo-express:
    image: mongo-express
    container_name: mongo-express-multi-vendor-ecommerce
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: mongoadmin
      ME_CONFIG_BASICAUTH_PASSWORD: mongopassword
    restart: always
    depends_on:
      - mongo

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-multi-vendor-ecommerce
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=multi-vendor-ecom
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    restart: always
    depends_on:
      - kafka

  es-hq:
    image: elastichq/elasticsearch-hq:latest
    container_name: es-hq-multi-vendor-ecommerce
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - elasticsearch

volumes:
  pg-multi-vendor-ecom:
  redis-multi-vendor-ecom:
  mongo-multi-vendor-ecom:
  zookeeper-data:
  kafka-data:
  es-data:
